
    create table alimentzioni (
        id_alimentazione integer generated by default as identity,
        alimentazione varchar(255) not null,
        primary key (id_alimentazione)
    );

    create table biciclette (
        id_freno integer unique,
        id_sospensione integer unique,
        id_veicolo integer not null,
        numero_marce integer not null,
        primary key (id_veicolo)
    );

    create table categorie (
        id_categoria integer generated by default as identity,
        categoria varchar(255) not null,
        primary key (id_categoria)
    );

    create table colori (
        id_colore integer generated by default as identity,
        colore varchar(255) not null,
        primary key (id_colore)
    );

    create table freni (
        id_freno integer generated by default as identity,
        freno varchar(255) not null unique,
        primary key (id_freno)
    );

    create table macchine (
        cilindrata integer not null,
        id_veicolo integer not null,
        porte integer not null,
        targa varchar(7) not null unique,
        primary key (id_veicolo)
    );

    create table moto (
        cilindrata integer not null,
        id_veicolo integer not null,
        targa varchar(5) not null unique,
        primary key (id_veicolo)
    );

    create table sospensioni (
        id_sospensione integer generated by default as identity,
        sospensione varchar(255) not null unique,
        primary key (id_sospensione)
    );

    create table veicoli (
        alimentazione integer,
        anno_produzione integer not null,
        categoria integer,
        colore integer,
        id_veicolo integer generated by default as identity,
        numero_ruote integer not null,
        tipo_veicolo varchar(50) not null,
        marca varchar(255) not null,
        modello varchar(255) not null,
        primary key (id_veicolo)
    );

    alter table if exists biciclette 
       add constraint FKhujb0c4ogf1nsk9hnxobqdeko 
       foreign key (id_freno) 
       references freni;

    alter table if exists biciclette 
       add constraint FK3cjv3q83j01ku3nc0j5l5l1o4 
       foreign key (id_sospensione) 
       references sospensioni;

    alter table if exists biciclette 
       add constraint FKscv2bmnwrgijta3evy3hjt50s 
       foreign key (id_veicolo) 
       references veicoli;

    alter table if exists macchine 
       add constraint FKpr95l56lnnp1uxuaemnx6fd2y 
       foreign key (id_veicolo) 
       references veicoli;

    alter table if exists moto 
       add constraint FKlgrryao9i5do671am9oe21cjs 
       foreign key (id_veicolo) 
       references veicoli;

    alter table if exists veicoli 
       add constraint FKsr36v1biky9738g54rma6x9ye 
       foreign key (alimentazione) 
       references alimentzioni;

    alter table if exists veicoli 
       add constraint FKgxsfdmeosk0k2bn4338lfrhi2 
       foreign key (categoria) 
       references categorie;

    alter table if exists veicoli 
       add constraint FKg6l2ldmbgjpmq6slnhrgq4yuq 
       foreign key (colore) 
       references colori;
